package org.rampart.lang.api.apiprotect;

import org.rampart.lang.api.RampartList;
import org.rampart.lang.api.core.RampartRule;
import org.rampart.lang.api.http.RampartHttpIOType;

/**
 * A rule for protecting an (HTTP) API endpoint.
 */
public interface RampartApi extends RampartRule {
    /**
     * Provides a list of URI patterns to which this rule should be applied.
     */
    RampartList getUriPatterns();

    /**
     * Indicates at which stage the rule should be executed - upon receiving
     * the request or when the response was generated by the application logic.
     */
    RampartHttpIOType getRequestProcessingStage();
}
